"""Constants for babybuddy tests."""

from datetime import datetime, timedelta
import os
from typing import Final

from zoneinfo import ZoneInfo

from custom_components.babybuddy.const import (
    ATTR_AMOUNT,
    ATTR_BIRTH_DATE,
    ATTR_BMI,
    ATTR_COLOR,
    ATTR_END,
    ATTR_FIRST_NAME,
    ATTR_HEAD_CIRCUMFERENCE_UNDERSCORE,
    ATTR_HEIGHT,
    ATTR_LAST_NAME,
    ATTR_METHOD,
    ATTR_MILESTONE,
    ATTR_NAP,
    ATTR_NOTE,
    ATTR_NOTES,
    ATTR_START,
    ATTR_TIMER,
    ATTR_TYPE,
    ATTR_WEIGHT,
    CONF_FEEDING_UNIT,
    CONF_WEIGHT_UNIT,
    DEFAULT_PATH,
    DEFAULT_SCAN_INTERVAL,
)
from homeassistant.const import (
    ATTR_DATE,
    ATTR_TEMPERATURE,
    ATTR_TIME,
    CONF_API_KEY,
    CONF_HOST,
    CONF_PATH,
    CONF_PORT,
    CONF_SCAN_INTERVAL,
    TEMPERATURE,
    UnitOfMass,
    UnitOfTemperature,
    UnitOfVolume,
)
import homeassistant.util.dt as dt_util

ATTR_INT_10: Final[int] = 10
ATTR_STEP_ID_USER: Final[str] = "user"

BABY_BUDDY_HOST = os.environ.get("BABY_BUDDY_HOST")
BABY_BUDDY_PORT = int(os.environ.get("BABY_BUDDY_PORT"))
API_KEY = os.environ.get("API_KEY")

MOCK_CONFIG = {
    CONF_HOST: BABY_BUDDY_HOST,
    CONF_PORT: BABY_BUDDY_PORT,
    CONF_PATH: DEFAULT_PATH,
    CONF_API_KEY: API_KEY,
}
INVALID_CONFIG_CONNECTERROR = {
    **MOCK_CONFIG,
    CONF_PATH: "lorem",
}
INVALID_CONFIG_AUTHORIZATIONERROR = {
    **MOCK_CONFIG,
    CONF_API_KEY: "lorem",
}
MOCK_OPTIONS = {
    TEMPERATURE: UnitOfTemperature.CELSIUS,
    CONF_WEIGHT_UNIT: UnitOfMass.GRAMS,
    CONF_FEEDING_UNIT: UnitOfVolume.MILLILITERS,
    CONF_SCAN_INTERVAL: DEFAULT_SCAN_INTERVAL,
}

MOCK_DATE_NOW: Final = dt_util.now().date()
MOCK_DATETIME_NOW: Final = datetime(2003, 1, 2, 1, 23, tzinfo=ZoneInfo("UTC"))
MOCK_DURATION: Final[timedelta] = timedelta(minutes=12, seconds=3)
MOCK_NOTES: Final[str] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
MOCK_NUMBER: Final = 123.0

MOCK_SERVICE_ADD_CHILD_SCHEMA = {
    ATTR_BIRTH_DATE: MOCK_DATE_NOW,
    ATTR_FIRST_NAME: "lorem",
    ATTR_LAST_NAME: "ipsum",
}
MOCK_SERVICE_ADD_BMI_SCHEMA = {
    ATTR_BMI: MOCK_NUMBER,
    ATTR_DATE: MOCK_DATE_NOW,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_DIAPER_CHANGE = {
    ATTR_TIME: MOCK_DATETIME_NOW,
    ATTR_NOTES: MOCK_NOTES,
    ATTR_TYPE: "Wet and Solid",
    ATTR_COLOR: "Black",
    ATTR_AMOUNT: MOCK_NUMBER,
}
MOCK_SERVICE_ADD_HEAD_CIRCUMFERENCE = {
    ATTR_HEAD_CIRCUMFERENCE_UNDERSCORE: MOCK_NUMBER,
    ATTR_DATE: MOCK_DATE_NOW,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_HEIGHT = {
    ATTR_HEIGHT: MOCK_NUMBER,
    ATTR_DATE: MOCK_DATE_NOW,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_NOTE = {
    ATTR_TIME: MOCK_DATETIME_NOW,
    ATTR_NOTE: MOCK_NOTES,
}
MOCK_SERVICE_ADD_PUMPING = {
    ATTR_AMOUNT: MOCK_NUMBER,
    ATTR_TIME: MOCK_DATETIME_NOW,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_TEMPERATURE = {
    ATTR_TEMPERATURE: 102.3,
    ATTR_TIME: MOCK_DATETIME_NOW,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_WEIGHT = {
    ATTR_DATE: MOCK_DATE_NOW,
    ATTR_NOTES: MOCK_NOTES,
    ATTR_WEIGHT: MOCK_NUMBER,
}
MOCK_SERVICE_ADD_FEEDING = {
    ATTR_TYPE: "Breast milk",
    ATTR_METHOD: "Bottle",
    ATTR_AMOUNT: MOCK_NUMBER,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_FEEDING_START_STOP = {
    **MOCK_SERVICE_ADD_FEEDING,
    ATTR_START: MOCK_DATETIME_NOW - MOCK_DURATION,
    ATTR_END: MOCK_DATETIME_NOW,
}
MOCK_SERVICE_ADD_FEEDING_TIMER = {
    **MOCK_SERVICE_ADD_FEEDING,
    ATTR_TIMER: True,
}
MOCK_SERVICE_ADD_PUMPING = {
    ATTR_AMOUNT: MOCK_NUMBER,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_PUMPING_START_STOP = {
    **MOCK_SERVICE_ADD_PUMPING,
    ATTR_START: MOCK_DATETIME_NOW - MOCK_DURATION,
    ATTR_END: MOCK_DATETIME_NOW,
}
MOCK_SERVICE_ADD_PUMPING_TIMER = {
    **MOCK_SERVICE_ADD_PUMPING,
    ATTR_TIMER: True,
}
MOCK_SERVICE_ADD_SLEEP = {
    ATTR_NAP: True,
    ATTR_NOTES: MOCK_NOTES,
}
MOCK_SERVICE_ADD_SLEEP_START_STOP = {
    **MOCK_SERVICE_ADD_SLEEP,
    ATTR_START: MOCK_DATETIME_NOW - MOCK_DURATION,
    ATTR_END: MOCK_DATETIME_NOW,
}
MOCK_SERVICE_ADD_SLEEP_TIMER = {
    **MOCK_SERVICE_ADD_SLEEP,
    ATTR_TIMER: True,
}
MOCK_SERVICE_ADD_TUMMY_TIME = {
    ATTR_MILESTONE: MOCK_NOTES,
}
MOCK_SERVICE_ADD_TUMMY_TIME_START_STOP = {
    **MOCK_SERVICE_ADD_TUMMY_TIME,
    ATTR_START: MOCK_DATETIME_NOW - MOCK_DURATION,
    ATTR_END: MOCK_DATETIME_NOW,
}
MOCK_SERVICE_ADD_TUMMY_TIME_TIMER = {
    **MOCK_SERVICE_ADD_TUMMY_TIME,
    ATTR_TIMER: True,
}

MOCK_BABY_NAME = f"{MOCK_SERVICE_ADD_CHILD_SCHEMA[ATTR_FIRST_NAME]}_{MOCK_SERVICE_ADD_CHILD_SCHEMA[ATTR_LAST_NAME]}"
MOCK_BABY_SENSOR_ID = f"sensor.baby_{MOCK_BABY_NAME}"
MOCK_BABY_SWITCH_ID = f"switch.{MOCK_BABY_NAME}_timer"
