name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  lint-ruff:
    name: lint-ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check
