name: Spell Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/translations/*.json'
  push:
    branches:
      - main
    paths-ignore:
      - '**/translations/*.json'

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@main
        with:
          config: cspell.json
